<div class="col-md-3 col-sm-6 col-xs-6 iblog-item">
        <article class="common-blog-post animated fadeInRight clearfix">
          <figure> <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="Image"/></a> </figure>
          <div class="text-content clearfix">
            <h5><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h5>
            <div class="entry-meta">
              <time><i class="fa fa-calendar"></i> &nbsp;[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
            </div>
            <div class="for-border"></div>
            <p class="desc">[field:description function="cn_substr(@me,160)"/]...</p>
          </div>
        </article>
        <a class="read-more" href="[field:arcurl/]">阅读更多</a> </div>