<div class="blog-article hentry format-image">
            <figure> <a class="swipebox-x" href="[field:arcurl/]"> <img class="img-responsive" alt="Post Image" src="[field:picname/]"/> </a> </figure>
            <div class="entry-summary post-summary">
              <header class="entry-header">
                <h2 class="entry-title post-title"> <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a> </h2>
              </header>
              <div class="entry-meta post-meta">
                <ul>
                  <li class="entry-date date">
                    <time class="entry-date" datetime="[field:pubdate function="MyDate('Y-m-d',@me)"/]">[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
                  </li>
                  <li class="tags"><a href="[field:typeurl/]">[field:typename/]</a></li>
                  <li class="byline author vcard">by <a href="javascript:void(0)" class="fn">[field:writer/]</a> </li>
                </ul>
              </div>
              <div class="entry-content">
                <p>[field:description function="cn_substr(@me,500)"/]...</p>
              </div>
              <a href="[field:arcurl/]" class="read-more-link">查看详细</a> </div>
          </div>