
            <article class="content clearfix hentry">
              <div class="row">
                <div class="col-md-6 iwhy-img">
                  <figure><img  src="[field:typeimg/]" alt="Image"/></figure>
                </div>
                <div class="col-md-6 iwhy-text">
                  <h5><a rel="bookmark">[field:typename/]</a></h5>
                  <div class="whytab-text">
                    <p>[field:description/]</p>
                  </div>
                  <a class="read-more" href="http://wpa.qq.com/msgrd?v=3&amp;uin=[field:global.cfg_kfqq/]&amp;site=qq&amp;menu=yes" target="_blank">立即咨询</a> </div>
              </div>
            </article>
            