<div class="portfolio-item isotope-item col-sm-4 col-xs-6">
                <article>
                  <figure class="glass-animation"> <a class="swipebox" href="[field:picname/]"> <span class="background"></span> <span class="glass"><span class="circle"><i class="handle"></i></span></span> <img class="img-responsive" src="[field:picname/]" alt="Photo"/> </a> </figure>
                  <h5 class="item-title"> <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a> </h5>
                  <div class="flex separator"> <span class="line"></span> <span class="wrap"><span class="square"></span></span> </div>
                </article>
              </div>