<div class="col-md-3 col-sm-6 col-xs-6 text-center iport-item">
        <div class="common-doctor animated fadeInUp clearfix">
          <figure> <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="Image" /></a> </figure>
          <div class="text-content">
            <h5 class="iport-title" title="[field:title/]"><a href="[field:arcurl/]">[field:title/]</a></h5>
            <div class="for-border"></div>
          </div>
        </div>
      </div>