<?php
$z[0]=Array("type","\r\n          <h3 class=\"title dark-title\"><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n          ",211,352);
$z[0][4]=array();
$z[0][4]['typeid']="2";
$z[1]=Array("sql"," \r\n              \r\n              [field:content  function='cn_substr(html2text(@me),500)'/]...\r\n              \r\n              ",414,611);
$z[1][4]=array();
$z[1][4]['sql']="Select content from dede_arctype where id=2";
$z[2]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\"><i class=\"fa fa-caret-right\"></i> &nbsp;[field:typename/]</a></li>\r\n            ",995,1168);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['row']="6";
$z[3]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a>",1387,1471);
$z[3][4]=array();
$z[3][4]['typeid']="3";
$z[4]=Array("global","",2598,2624);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",2775,2799);
$z[5][4]=array();
$z[5][4]['name']="cfg_weibo";
$z[6]=Array("global","",2880,2906);
$z[6][4]=array();
$z[6][4]['name']="cfg_qqweibo";
$z[7]=Array("global","",3031,3054);
$z[7][4]=array();
$z[7][4]['name']="cfg_kfqq";
$z[8]=Array("global","",3164,3188);
$z[8][4]=array();
$z[8][4]['name']="cfg_email";

?>