<?php
$z[0]=Array("global","",204,229);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("arclist","\r\n          <li>\r\n            <figure><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"/></a></figure>\r\n            <div class=\"sn-wrapper\">\r\n              <p class=\"s-desc\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n              <span class=\"comments\"><i class=\"fa fa-calendar\"></i> &nbsp;[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </div>\r\n          </li>\r\n          ",1023,1518);
$z[1][4]=array();
$z[1][4]['typeid']="3";
$z[1][4]['row']="3";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";

?>